again

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,6 +19,8 @@ jobs:
   build:
     name: Build IPMHub variant of AVM modules
     runs-on: ubuntu-latest
+    outputs:
+      testsOutcome: ${{ steps.test.outputs.outcome }}
     steps:
     - uses: actions/checkout@v4
       with:
@@ -45,12 +47,18 @@ jobs:
 
     - name: Test the IPMHub packages
       id: test
-      if: ${{ github.event.inputs.skipTests == 'false' }}
+      if: ${{ github.event.inputs.skipTests == false }}
       run: |
         $AvmPackageBuildRoot = Join-Path -Path (Get-Location).Path -ChildPath "build"
         $TestRoot = Join-Path -Path (Get-Location).Path -ChildPath "build-tests"
         & ./src/scripts/prepare-tests.ps1 -AvmPackageBuildRoot $AvmPackageBuildRoot -TestRootPath $TestRoot
         & ./src/scripts/run-tests.ps1 -TestRootPath $TestRoot
+
+        if ($?) {
+          echo "outcome=success" >> $GITHUB_OUTPUT
+        } else {
+          echo "outcome=failure" >> $GITHUB_OUTPUT
+        }
       shell: pwsh
       continue-on-error: true
 
@@ -62,13 +70,13 @@ jobs:
       with:
         name: avm-buildresults
         path: buildresults.zip
-        retention-days: ${{ steps.test.outcome == 'success' && 31 || 3 }}
+        retention-days: ${{ steps.test.outcome == success && 31 || 3 }}
 
   publish:
     name: Publish IPMHub packages
     runs-on: ubuntu-latest
     needs: build
-    if: ${{ github.event.inputs.shouldPublish == 'true' && needs.build.outputs.test.outcome == 'success' }}
+    if: ${{ github.event.inputs.shouldPublish == true && needs.build.outputs.testsOutcome.outcome == 'success' }}
     steps:
     - uses: actions/checkout@v4
       with:
@@ -91,6 +99,12 @@ jobs:
         Get-ChildItem
         $AvmPackageBuildRoot = Join-Path -Path (Get-Location).Path -ChildPath "avm-buildresults"
         & ./src/scripts/publish-creation.ps1 -AvmPackageBuildRoot $AvmPackageBuildRoot -PackageCreationApi $env:PACKAGE_CREATION_API
+
+        if ($?) {
+          echo "outcome=success" >> $GITHUB_OUTPUT
+        } else {
+          echo "outcome=failure" >> $GITHUB_OUTPUT
+        }
       shell: pwsh
       working-directory: ./avm-buildresults
       env:
@@ -118,8 +132,9 @@ jobs:
     - uses: actions/checkout@v4
       with:
         path: src
+
     - name: Notify on TESTS Failure
-      if: ${{ needs.build.outputs.test.outcome != 'success' }}
+      if: ${{ needs.build.outputs.testsOutcome.outcome == 'failure' }}
       run: |
         Import-Module ./src/scripts/avm-to-ipm-module.psm1
         $GitHubRunUri = "https://github.com/{0}/actions/runs/{1}" -f $env:GITHUB_REPOSITORY, $env:GITHUB_RUN_ID
@@ -129,7 +144,7 @@ jobs:
         TEAMS_TOKEN: ${{ secrets.TEAMS_WEBHOOK_URL }}
 
     - name: Notify on publication failure
-      if: ${{ needs.publish.outputs.publish.outcome != 'success' }}
+      if: ${{ needs.publish.result == 'failure' }}
       run: |
         Import-Module ./src/scripts/avm-to-ipm-module.psm1
         $GitHubRunUri = "https://github.com/{0}/actions/runs/{1}" -f $env:GITHUB_REPOSITORY, $env:GITHUB_RUN_ID
@@ -139,7 +154,7 @@ jobs:
         TEAMS_TOKEN: ${{ secrets.TEAMS_WEBHOOK_URL }}
 
     - name: Notify on publication success
-      if: ${{ needs.publish.outputs.publish.outcome == 'success' }}
+      if: ${{ needs.publish.result == 'success' }}
       run: |
         Import-Module ./src/scripts/avm-to-ipm-module.psm1
         $GitHubRunUri = "https://github.com/{0}/actions/runs/{1}" -f $env:GITHUB_REPOSITORY, $env:GITHUB_RUN_ID
